name: TEST - OpenAPI

on:
  push:
    branches: [ feat/open-api ]

  workflow_dispatch:

jobs:
  schema-generation:
      runs-on: ubuntu-latest
      steps:
      - name: Install crystal
        uses: crystal-lang/install-crystal@v1.6.0
        with: 
            crystal: 1.3.2
      - run: apt-get update && apt-get install curl
      - uses: actions/checkout@v2
      - run: shards install
      - name: Generate OpenAPI schema
        run: crystal run ./src/openapi_generator.cr
      - uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: "feat(schema): updated schema for changes in ${GITHUB_SHA}"
          file_pattern: "openapi.yaml"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Checkout part env repo
        uses: actions/checkout@v2
        with:
          repository: place-labs/partner-environment
          path: main
      - name: Spin up PlaceOS
        working-directory: ./main
        run: ./placeos start --verbose
        env:
          PLACE_EMAIL: support@place.tech
          PLACE_PASSWORD: development
      - name: Set Auth Token
        run: |
            token=$(  curl --location --request POST "https://localhost:8443/auth/oauth/token?grant_type=password&username=support@place.tech&password=development&client_id=b52e653071c45353dbff4e8f47d51cdf" -k | jq -r '.access_token')
            
            echo "ORG=$token" >> "$GITHUB_ENV"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm install dredd@14.0.0 --global
      - run: dredd
